/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rzjHmYh7HtQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export default function Page() {
  async function createInvoice(formData: FormData) {
    'use server'

    const rawFormData = {
      customerId: formData.get('customerId'),
      amount: formData.get('amount'),
      status: formData.get('status'),
    }

    // mutate data
    // revalidate cache
  }

  return <form action={createInvoice}>...</form>
}

export function CreateProgram() {
  return (
    <>
      <header className="flex items-center justify-between px-6 py-4 bg-white dark:bg-gray-800 shadow">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100">New Loyalty Program</h1>
        <div className="flex items-center space-x-4">
          <Button variant="outline">
            <PlusIcon className="mr-2 h-4 w-4" />
            Add new tier
          </Button>
        </div>
      </header>
      <div className="flex flex-col items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
        <div className="w-full max-w-3xl p-6 bg-white rounded-lg shadow-md dark:bg-gray-800">
          <div className="space-y-6">
            <div className="text-center pt-6">
              <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100">Loyalty Program Details</h2>
            </div>
            <div className="grid grid-cols-1 gap-4">
              <div>
                <label
                  className="block text-lg font-medium text-gray-700 dark:text-gray-300 mb-1"
                  htmlFor="program-name"
                >
                  Name
                </label>
                <div className="mt-1">
                  <input
                    className="block w-full px-3 py-2 border border-gray-200 border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-200 dark:border-gray-800"
                    id="program-name"
                    placeholder="Enter loyalty program name"
                    type="text"
                  />
                </div>
              </div>
              <div>
                <label
                  className="block text-lg font-medium text-gray-700 dark:text-gray-300 mb-1"
                  htmlFor="program-description"
                >
                  Description
                </label>
                <div className="mt-1">
                  <textarea
                    className="block w-full px-3 py-2 border border-gray-200 border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-200 dark:border-gray-800"
                    id="program-description"
                    placeholder="Enter loyalty program description"
                    rows={3}
                  />
                </div>
              </div>
            </div>
            <div className="flex justify-end">
              <Button variant="outline">
                <PlusIcon className="mr-2 h-4 w-4" />
                Add New Tier
              </Button>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

function PlusIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
