/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/m1mnsVdJlFe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import {retrieveProducts, retrieveUser} from "@/app/cart/actions";
import AddToCartButton from "@/components/Cart";
import {resolveTier} from "@/lib/resolve-tier";
import {getCurrentCartValue} from "@/app/cart";
import {TierButton} from "@/components/TierButton";
import {TierMsgButton} from "@/components/TierMsgButton";

export async function ShopperExperience() {
    const products = await retrieveProducts();

  return (
    <section className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 md:gap-8 lg:gap-10 px-4 md:px-6 lg:px-8 py-12 md:py-16 lg:py-20 relative">
      <div className="absolute top-4 right-4 flex items-center gap-4">
        <TierButton />
        <TierMsgButton />
        <Button className="bg-black text-white font-bold px-8 py-4" size="lg" variant="default">
          Checkout
        </Button>
      </div>
        {products.map(product => {
            return (
                <div key={product.guid} className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-950">
                <div className="relative">
                    <img
                        alt="Product 1"
                        className="w-full h-60 object-cover"
                        height={300}
                        src="/placeholder.svg"
                        style={{
                            aspectRatio: "400/300",
                            objectFit: "cover",
                        }}
                        width={400}
                    />
                </div>
                <div className="p-4">
                    <h3 className="text-lg font-semibold mb-1">{product.name}</h3>
                    <p className="text-gray-500 dark:text-gray-400 text-sm mb-2">{product.description}</p>
                    <div className="flex items-center justify-between">
                        <span className="text-lg font-semibold">${product.price}</span>
                        <AddToCartButton product={product} />
                    </div>
                </div>
            </div>)
        })}
    </section>
  )
}
